/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProjectStatus = IDL.Variant({
  'Closed' : IDL.Null,
  'Active' : IDL.Null,
  'Draft' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ProjectCategory = IDL.Variant({
  'Bridal' : IDL.Null,
  'MusicVideo' : IDL.Null,
  'ECommerce' : IDL.Null,
  'Fashion' : IDL.Null,
  'Jewellery' : IDL.Null,
  'International' : IDL.Null,
  'WebSeries' : IDL.Null,
  'BrandPromotion' : IDL.Null,
  'Catalogue' : IDL.Null,
});
export const ProjectInput = IDL.Record({
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : Timestamp,
  'category' : ProjectCategory,
  'requirements' : IDL.Text,
  'budget' : IDL.Text,
});
export const ProjectId = IDL.Nat;
export const ProjectRecord = IDL.Record({
  'id' : ProjectId,
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'deadline' : Timestamp,
  'updatedAt' : Timestamp,
  'category' : ProjectCategory,
  'requirements' : IDL.Text,
  'budget' : IDL.Text,
  'assignedCandidates' : IDL.Vec(IDL.Principal),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NotificationType = IDL.Variant({
  'RegistrationUpdate' : IDL.Null,
  'Reminder' : IDL.Null,
  'Announcement' : IDL.Null,
  'ProjectMatch' : IDL.Null,
  'Offer' : IDL.Null,
});
export const CandidateId = IDL.Principal;
export const PaymentStatus = IDL.Variant({
  'NotPaid' : IDL.Null,
  'Paid' : IDL.Null,
  'Verified' : IDL.Null,
});
export const RegistrationStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Suspended' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CandidateProfile = IDL.Record({
  'id' : CandidateId,
  'age' : IDL.Nat,
  'height' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'measurements' : IDL.Text,
  'phone' : IDL.Text,
  'registrationStatus' : RegistrationStatus,
  'portfolioImages' : IDL.Vec(ExternalBlob),
  'principalId' : IDL.Principal,
});
export const AppConfig = IDL.Record({
  'stripePublicKey' : IDL.Text,
  'instagramHandle' : IDL.Text,
  'email' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'paymentAmount' : IDL.Nat,
});
export const NotificationId = IDL.Nat;
export const NotificationRecord = IDL.Record({
  'id' : NotificationId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'senderPrincipal' : IDL.Principal,
  'message' : IDL.Text,
  'recipientPrincipal' : IDL.Principal,
});
export const PaymentId = IDL.Nat;
export const PaymentRecordStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'id' : PaymentId,
  'status' : PaymentRecordStatus,
  'createdAt' : Timestamp,
  'stripePaymentId' : IDL.Text,
  'amount' : IDL.Nat,
  'principalId' : IDL.Principal,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const CandidateProfileInput = IDL.Record({
  'age' : IDL.Nat,
  'height' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'measurements' : IDL.Text,
  'phone' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addProject' : IDL.Func([ProjectInput], [ProjectRecord], []),
  'approveCandidate' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCandidateToProject' : IDL.Func([ProjectId, IDL.Principal], [], []),
  'broadcastNotification' : IDL.Func(
      [IDL.Vec(IDL.Principal), IDL.Text, NotificationType],
      [],
      [],
    ),
  'createCheckoutSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateDetail' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CandidateProfile)],
      ['query'],
    ),
  'getConfig' : IDL.Func([], [AppConfig], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationRecord)], ['query']),
  'getMyPaymentStatus' : IDL.Func([], [IDL.Opt(PaymentRecord)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(CandidateProfile)], ['query']),
  'getMyProjects' : IDL.Func([], [IDL.Vec(ProjectRecord)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllCandidates' : IDL.Func([], [IDL.Vec(CandidateProfile)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(ProjectRecord)], ['query']),
  'markNotificationRead' : IDL.Func([NotificationId], [], []),
  'recordPayment' : IDL.Func([IDL.Text], [PaymentRecord], []),
  'registerCandidate' : IDL.Func(
      [CandidateProfileInput],
      [CandidateProfile],
      [],
    ),
  'rejectCandidate' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'sendNotification' : IDL.Func(
      [IDL.Principal, IDL.Text, NotificationType],
      [NotificationRecord],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateConfig' : IDL.Func([AppConfig], [], []),
  'updateMyProfile' : IDL.Func([CandidateProfileInput], [CandidateProfile], []),
  'updateProject' : IDL.Func([ProjectId, ProjectInput], [ProjectRecord], []),
  'uploadPortfolioImages' : IDL.Func([IDL.Vec(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProjectStatus = IDL.Variant({
    'Closed' : IDL.Null,
    'Active' : IDL.Null,
    'Draft' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ProjectCategory = IDL.Variant({
    'Bridal' : IDL.Null,
    'MusicVideo' : IDL.Null,
    'ECommerce' : IDL.Null,
    'Fashion' : IDL.Null,
    'Jewellery' : IDL.Null,
    'International' : IDL.Null,
    'WebSeries' : IDL.Null,
    'BrandPromotion' : IDL.Null,
    'Catalogue' : IDL.Null,
  });
  const ProjectInput = IDL.Record({
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : Timestamp,
    'category' : ProjectCategory,
    'requirements' : IDL.Text,
    'budget' : IDL.Text,
  });
  const ProjectId = IDL.Nat;
  const ProjectRecord = IDL.Record({
    'id' : ProjectId,
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'deadline' : Timestamp,
    'updatedAt' : Timestamp,
    'category' : ProjectCategory,
    'requirements' : IDL.Text,
    'budget' : IDL.Text,
    'assignedCandidates' : IDL.Vec(IDL.Principal),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NotificationType = IDL.Variant({
    'RegistrationUpdate' : IDL.Null,
    'Reminder' : IDL.Null,
    'Announcement' : IDL.Null,
    'ProjectMatch' : IDL.Null,
    'Offer' : IDL.Null,
  });
  const CandidateId = IDL.Principal;
  const PaymentStatus = IDL.Variant({
    'NotPaid' : IDL.Null,
    'Paid' : IDL.Null,
    'Verified' : IDL.Null,
  });
  const RegistrationStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Suspended' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CandidateProfile = IDL.Record({
    'id' : CandidateId,
    'age' : IDL.Nat,
    'height' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'measurements' : IDL.Text,
    'phone' : IDL.Text,
    'registrationStatus' : RegistrationStatus,
    'portfolioImages' : IDL.Vec(ExternalBlob),
    'principalId' : IDL.Principal,
  });
  const AppConfig = IDL.Record({
    'stripePublicKey' : IDL.Text,
    'instagramHandle' : IDL.Text,
    'email' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'paymentAmount' : IDL.Nat,
  });
  const NotificationId = IDL.Nat;
  const NotificationRecord = IDL.Record({
    'id' : NotificationId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'senderPrincipal' : IDL.Principal,
    'message' : IDL.Text,
    'recipientPrincipal' : IDL.Principal,
  });
  const PaymentId = IDL.Nat;
  const PaymentRecordStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'id' : PaymentId,
    'status' : PaymentRecordStatus,
    'createdAt' : Timestamp,
    'stripePaymentId' : IDL.Text,
    'amount' : IDL.Nat,
    'principalId' : IDL.Principal,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const CandidateProfileInput = IDL.Record({
    'age' : IDL.Nat,
    'height' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'measurements' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addProject' : IDL.Func([ProjectInput], [ProjectRecord], []),
    'approveCandidate' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCandidateToProject' : IDL.Func([ProjectId, IDL.Principal], [], []),
    'broadcastNotification' : IDL.Func(
        [IDL.Vec(IDL.Principal), IDL.Text, NotificationType],
        [],
        [],
      ),
    'createCheckoutSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateDetail' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CandidateProfile)],
        ['query'],
      ),
    'getConfig' : IDL.Func([], [AppConfig], ['query']),
    'getMyNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationRecord)],
        ['query'],
      ),
    'getMyPaymentStatus' : IDL.Func([], [IDL.Opt(PaymentRecord)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(CandidateProfile)], ['query']),
    'getMyProjects' : IDL.Func([], [IDL.Vec(ProjectRecord)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllCandidates' : IDL.Func([], [IDL.Vec(CandidateProfile)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(ProjectRecord)], ['query']),
    'markNotificationRead' : IDL.Func([NotificationId], [], []),
    'recordPayment' : IDL.Func([IDL.Text], [PaymentRecord], []),
    'registerCandidate' : IDL.Func(
        [CandidateProfileInput],
        [CandidateProfile],
        [],
      ),
    'rejectCandidate' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'sendNotification' : IDL.Func(
        [IDL.Principal, IDL.Text, NotificationType],
        [NotificationRecord],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateConfig' : IDL.Func([AppConfig], [], []),
    'updateMyProfile' : IDL.Func(
        [CandidateProfileInput],
        [CandidateProfile],
        [],
      ),
    'updateProject' : IDL.Func([ProjectId, ProjectInput], [ProjectRecord], []),
    'uploadPortfolioImages' : IDL.Func([IDL.Vec(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };