/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppConfig {
  'stripePublicKey' : string,
  'instagramHandle' : string,
  'email' : string,
  'whatsappNumber' : string,
  'paymentAmount' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type CandidateId = Principal;
export interface CandidateProfile {
  'id' : CandidateId,
  'age' : bigint,
  'height' : string,
  'paymentStatus' : PaymentStatus,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'updatedAt' : Timestamp,
  'measurements' : string,
  'phone' : string,
  'registrationStatus' : RegistrationStatus,
  'portfolioImages' : Array<ExternalBlob>,
  'principalId' : Principal,
}
export interface CandidateProfileInput {
  'age' : bigint,
  'height' : string,
  'city' : string,
  'name' : string,
  'email' : string,
  'measurements' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export type NotificationId = bigint;
export interface NotificationRecord {
  'id' : NotificationId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'senderPrincipal' : Principal,
  'message' : string,
  'recipientPrincipal' : Principal,
}
export type NotificationType = { 'RegistrationUpdate' : null } |
  { 'Reminder' : null } |
  { 'Announcement' : null } |
  { 'ProjectMatch' : null } |
  { 'Offer' : null };
export type PaymentId = bigint;
export interface PaymentRecord {
  'id' : PaymentId,
  'status' : PaymentRecordStatus,
  'createdAt' : Timestamp,
  'stripePaymentId' : string,
  'amount' : bigint,
  'principalId' : Principal,
}
export type PaymentRecordStatus = { 'Failed' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export type PaymentStatus = { 'NotPaid' : null } |
  { 'Paid' : null } |
  { 'Verified' : null };
export type ProjectCategory = { 'Bridal' : null } |
  { 'MusicVideo' : null } |
  { 'ECommerce' : null } |
  { 'Fashion' : null } |
  { 'Jewellery' : null } |
  { 'International' : null } |
  { 'WebSeries' : null } |
  { 'BrandPromotion' : null } |
  { 'Catalogue' : null };
export type ProjectId = bigint;
export interface ProjectInput {
  'status' : ProjectStatus,
  'title' : string,
  'description' : string,
  'deadline' : Timestamp,
  'category' : ProjectCategory,
  'requirements' : string,
  'budget' : string,
}
export interface ProjectRecord {
  'id' : ProjectId,
  'status' : ProjectStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'deadline' : Timestamp,
  'updatedAt' : Timestamp,
  'category' : ProjectCategory,
  'requirements' : string,
  'budget' : string,
  'assignedCandidates' : Array<Principal>,
}
export type ProjectStatus = { 'Closed' : null } |
  { 'Active' : null } |
  { 'Draft' : null };
export type RegistrationStatus = { 'Approved' : null } |
  { 'Suspended' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProject' : ActorMethod<[ProjectInput], ProjectRecord>,
  'approveCandidate' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCandidateToProject' : ActorMethod<[ProjectId, Principal], undefined>,
  'broadcastNotification' : ActorMethod<
    [Array<Principal>, string, NotificationType],
    undefined
  >,
  'createCheckoutSession' : ActorMethod<[string, string], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateDetail' : ActorMethod<[Principal], [] | [CandidateProfile]>,
  'getConfig' : ActorMethod<[], AppConfig>,
  'getMyNotifications' : ActorMethod<[], Array<NotificationRecord>>,
  'getMyPaymentStatus' : ActorMethod<[], [] | [PaymentRecord]>,
  'getMyProfile' : ActorMethod<[], [] | [CandidateProfile]>,
  'getMyProjects' : ActorMethod<[], Array<ProjectRecord>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllCandidates' : ActorMethod<[], Array<CandidateProfile>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'listProjects' : ActorMethod<[], Array<ProjectRecord>>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'recordPayment' : ActorMethod<[string], PaymentRecord>,
  'registerCandidate' : ActorMethod<[CandidateProfileInput], CandidateProfile>,
  'rejectCandidate' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'sendNotification' : ActorMethod<
    [Principal, string, NotificationType],
    NotificationRecord
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateConfig' : ActorMethod<[AppConfig], undefined>,
  'updateMyProfile' : ActorMethod<[CandidateProfileInput], CandidateProfile>,
  'updateProject' : ActorMethod<[ProjectId, ProjectInput], ProjectRecord>,
  'uploadPortfolioImages' : ActorMethod<[Array<ExternalBlob>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];