/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AppConfig {
    stripePublicKey: string;
    instagramHandle: string;
    email: string;
    whatsappNumber: string;
    paymentAmount: bigint;
}
export interface PaymentRecord {
    id: PaymentId;
    status: PaymentRecordStatus;
    createdAt: Timestamp;
    stripePaymentId: string;
    amount: bigint;
    principalId: Principal;
}
export interface CandidateProfileInput {
    age: bigint;
    height: string;
    city: string;
    name: string;
    email: string;
    measurements: string;
    phone: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface NotificationRecord {
    id: NotificationId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
    senderPrincipal: Principal;
    message: string;
    recipientPrincipal: Principal;
}
export interface ProjectInput {
    status: ProjectStatus;
    title: string;
    description: string;
    deadline: Timestamp;
    category: ProjectCategory;
    requirements: string;
    budget: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface CandidateProfile {
    id: CandidateId;
    age: bigint;
    height: string;
    paymentStatus: PaymentStatus;
    city: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    measurements: string;
    phone: string;
    registrationStatus: RegistrationStatus;
    portfolioImages: Array<ExternalBlob>;
    principalId: Principal;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ProjectRecord {
    id: ProjectId;
    status: ProjectStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    deadline: Timestamp;
    updatedAt: Timestamp;
    category: ProjectCategory;
    requirements: string;
    budget: string;
    assignedCandidates: Array<Principal>;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export type CandidateId = Principal;
export type PaymentId = bigint;
export type NotificationId = bigint;
export type ProjectId = bigint;
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum NotificationType {
    RegistrationUpdate = "RegistrationUpdate",
    Reminder = "Reminder",
    Announcement = "Announcement",
    ProjectMatch = "ProjectMatch",
    Offer = "Offer"
}
export enum PaymentRecordStatus {
    Failed = "Failed",
    Completed = "Completed",
    Pending = "Pending"
}
export enum PaymentStatus {
    NotPaid = "NotPaid",
    Paid = "Paid",
    Verified = "Verified"
}
export enum ProjectCategory {
    Bridal = "Bridal",
    MusicVideo = "MusicVideo",
    ECommerce = "ECommerce",
    Fashion = "Fashion",
    Jewellery = "Jewellery",
    International = "International",
    WebSeries = "WebSeries",
    BrandPromotion = "BrandPromotion",
    Catalogue = "Catalogue"
}
export enum ProjectStatus {
    Closed = "Closed",
    Active = "Active",
    Draft = "Draft"
}
export enum RegistrationStatus {
    Approved = "Approved",
    Suspended = "Suspended",
    Rejected = "Rejected",
    Pending = "Pending"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addProject(input: ProjectInput): Promise<ProjectRecord>;
    approveCandidate(candidateId: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignCandidateToProject(projectId: ProjectId, candidatePrincipal: Principal): Promise<void>;
    broadcastNotification(recipients: Array<Principal>, message: string, notificationType: NotificationType): Promise<void>;
    createCheckoutSession(successUrl: string, cancelUrl: string): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getCandidateDetail(candidateId: Principal): Promise<CandidateProfile | null>;
    getConfig(): Promise<AppConfig>;
    getMyNotifications(): Promise<Array<NotificationRecord>>;
    getMyPaymentStatus(): Promise<PaymentRecord | null>;
    getMyProfile(): Promise<CandidateProfile | null>;
    getMyProjects(): Promise<Array<ProjectRecord>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAllCandidates(): Promise<Array<CandidateProfile>>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listPayments(): Promise<Array<PaymentRecord>>;
    listProjects(): Promise<Array<ProjectRecord>>;
    markNotificationRead(notificationId: NotificationId): Promise<void>;
    recordPayment(stripeSessionId: string): Promise<PaymentRecord>;
    registerCandidate(input: CandidateProfileInput): Promise<CandidateProfile>;
    rejectCandidate(candidateId: Principal): Promise<void>;
    requestApproval(): Promise<void>;
    sendNotification(recipient: Principal, message: string, notificationType: NotificationType): Promise<NotificationRecord>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateConfig(newConfig: AppConfig): Promise<void>;
    updateMyProfile(input: CandidateProfileInput): Promise<CandidateProfile>;
    updateProject(projectId: ProjectId, input: ProjectInput): Promise<ProjectRecord>;
    uploadPortfolioImages(images: Array<ExternalBlob>): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, CandidateId as _CandidateId, CandidateProfile as _CandidateProfile, ExternalBlob as _ExternalBlob, NotificationId as _NotificationId, NotificationRecord as _NotificationRecord, NotificationType as _NotificationType, PaymentId as _PaymentId, PaymentRecord as _PaymentRecord, PaymentRecordStatus as _PaymentRecordStatus, PaymentStatus as _PaymentStatus, ProjectCategory as _ProjectCategory, ProjectId as _ProjectId, ProjectInput as _ProjectInput, ProjectRecord as _ProjectRecord, ProjectStatus as _ProjectStatus, RegistrationStatus as _RegistrationStatus, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addProject(arg0: ProjectInput): Promise<ProjectRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(to_candid_ProjectInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ProjectRecord_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(to_candid_ProjectInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ProjectRecord_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveCandidate(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveCandidate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveCandidate(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCandidateToProject(arg0: ProjectId, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCandidateToProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCandidateToProject(arg0, arg1);
            return result;
        }
    }
    async broadcastNotification(arg0: Array<Principal>, arg1: string, arg2: NotificationType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.broadcastNotification(arg0, arg1, to_candid_NotificationType_n22(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.broadcastNotification(arg0, arg1, to_candid_NotificationType_n22(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createCheckoutSession(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidateDetail(arg0: Principal): Promise<CandidateProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidateDetail(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidateDetail(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfig(): Promise<AppConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfig();
            return result;
        }
    }
    async getMyNotifications(): Promise<Array<NotificationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPaymentStatus(): Promise<PaymentRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPaymentStatus();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPaymentStatus();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<CandidateProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProjects(): Promise<Array<ProjectRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProjects();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProjects();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAllCandidates(): Promise<Array<CandidateProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllCandidates();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllCandidates();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPayments();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPayments();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<ProjectRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async recordPayment(arg0: string): Promise<PaymentRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(arg0);
                return from_candid_PaymentRecord_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(arg0);
            return from_candid_PaymentRecord_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerCandidate(arg0: CandidateProfileInput): Promise<CandidateProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCandidate(arg0);
                return from_candid_CandidateProfile_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCandidate(arg0);
            return from_candid_CandidateProfile_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectCandidate(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectCandidate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectCandidate(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async sendNotification(arg0: Principal, arg1: string, arg2: NotificationType): Promise<NotificationRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.sendNotification(arg0, arg1, to_candid_NotificationType_n22(this._uploadFile, this._downloadFile, arg2));
                return from_candid_NotificationRecord_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendNotification(arg0, arg1, to_candid_NotificationType_n22(this._uploadFile, this._downloadFile, arg2));
            return from_candid_NotificationRecord_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n57(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n57(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateConfig(arg0: AppConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConfig(arg0);
            return result;
        }
    }
    async updateMyProfile(arg0: CandidateProfileInput): Promise<CandidateProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0);
                return from_candid_CandidateProfile_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0);
            return from_candid_CandidateProfile_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: ProjectId, arg1: ProjectInput): Promise<ProjectRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_ProjectInput_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_ProjectRecord_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_ProjectInput_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_ProjectRecord_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadPortfolioImages(arg0: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPortfolioImages(await to_candid_vec_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPortfolioImages(await to_candid_vec_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
async function from_candid_CandidateProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CandidateProfile): Promise<CandidateProfile> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_NotificationRecord_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationRecord): NotificationRecord {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRecordStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecordStatus): PaymentRecordStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRecord_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecord): PaymentRecord {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectCategory_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectCategory): ProjectCategory {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectRecord_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectRecord): ProjectRecord {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationStatus): RegistrationStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CandidateProfile]): Promise<CandidateProfile | null> {
    return value.length === 0 ? null : await from_candid_CandidateProfile_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentRecord]): PaymentRecord | null {
    return value.length === 0 ? null : from_candid_PaymentRecord_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    status: _ProjectStatus;
    title: string;
    createdAt: _Timestamp;
    description: string;
    deadline: _Timestamp;
    updatedAt: _Timestamp;
    category: _ProjectCategory;
    requirements: string;
    budget: string;
    assignedCandidates: Array<Principal>;
}): {
    id: ProjectId;
    status: ProjectStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    deadline: Timestamp;
    updatedAt: Timestamp;
    category: ProjectCategory;
    requirements: string;
    budget: string;
    assignedCandidates: Array<Principal>;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n16(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        deadline: value.deadline,
        updatedAt: value.updatedAt,
        category: from_candid_ProjectCategory_n18(_uploadFile, _downloadFile, value.category),
        requirements: value.requirements,
        budget: value.budget,
        assignedCandidates: value.assignedCandidates
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CandidateId;
    age: bigint;
    height: string;
    paymentStatus: _PaymentStatus;
    city: string;
    name: string;
    createdAt: _Timestamp;
    email: string;
    updatedAt: _Timestamp;
    measurements: string;
    phone: string;
    registrationStatus: _RegistrationStatus;
    portfolioImages: Array<_ExternalBlob>;
    principalId: Principal;
}): Promise<{
    id: CandidateId;
    age: bigint;
    height: string;
    paymentStatus: PaymentStatus;
    city: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    updatedAt: Timestamp;
    measurements: string;
    phone: string;
    registrationStatus: RegistrationStatus;
    portfolioImages: Array<ExternalBlob>;
    principalId: Principal;
}> {
    return {
        id: value.id,
        age: value.age,
        height: value.height,
        paymentStatus: from_candid_PaymentStatus_n29(_uploadFile, _downloadFile, value.paymentStatus),
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        measurements: value.measurements,
        phone: value.phone,
        registrationStatus: from_candid_RegistrationStatus_n31(_uploadFile, _downloadFile, value.registrationStatus),
        portfolioImages: await from_candid_vec_n33(_uploadFile, _downloadFile, value.portfolioImages),
        principalId: value.principalId
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    notificationType: _NotificationType;
    createdAt: _Timestamp;
    isRead: boolean;
    senderPrincipal: Principal;
    message: string;
    recipientPrincipal: Principal;
}): {
    id: NotificationId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    isRead: boolean;
    senderPrincipal: Principal;
    message: string;
    recipientPrincipal: Principal;
} {
    return {
        id: value.id,
        notificationType: from_candid_NotificationType_n38(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        isRead: value.isRead,
        senderPrincipal: value.senderPrincipal,
        message: value.message,
        recipientPrincipal: value.recipientPrincipal
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    status: _PaymentRecordStatus;
    createdAt: _Timestamp;
    stripePaymentId: string;
    amount: bigint;
    principalId: Principal;
}): {
    id: PaymentId;
    status: PaymentRecordStatus;
    createdAt: Timestamp;
    stripePaymentId: string;
    amount: bigint;
    principalId: Principal;
} {
    return {
        id: value.id,
        status: from_candid_PaymentRecordStatus_n43(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        stripePaymentId: value.stripePaymentId,
        amount: value.amount,
        principalId: value.principalId
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n54(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Closed: null;
} | {
    Active: null;
} | {
    Draft: null;
}): ProjectStatus {
    return "Closed" in value ? ProjectStatus.Closed : "Active" in value ? ProjectStatus.Active : "Draft" in value ? ProjectStatus.Draft : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Bridal: null;
} | {
    MusicVideo: null;
} | {
    ECommerce: null;
} | {
    Fashion: null;
} | {
    Jewellery: null;
} | {
    International: null;
} | {
    WebSeries: null;
} | {
    BrandPromotion: null;
} | {
    Catalogue: null;
}): ProjectCategory {
    return "Bridal" in value ? ProjectCategory.Bridal : "MusicVideo" in value ? ProjectCategory.MusicVideo : "ECommerce" in value ? ProjectCategory.ECommerce : "Fashion" in value ? ProjectCategory.Fashion : "Jewellery" in value ? ProjectCategory.Jewellery : "International" in value ? ProjectCategory.International : "WebSeries" in value ? ProjectCategory.WebSeries : "BrandPromotion" in value ? ProjectCategory.BrandPromotion : "Catalogue" in value ? ProjectCategory.Catalogue : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NotPaid: null;
} | {
    Paid: null;
} | {
    Verified: null;
}): PaymentStatus {
    return "NotPaid" in value ? PaymentStatus.NotPaid : "Paid" in value ? PaymentStatus.Paid : "Verified" in value ? PaymentStatus.Verified : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Suspended: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): RegistrationStatus {
    return "Approved" in value ? RegistrationStatus.Approved : "Suspended" in value ? RegistrationStatus.Suspended : "Rejected" in value ? RegistrationStatus.Rejected : "Pending" in value ? RegistrationStatus.Pending : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    RegistrationUpdate: null;
} | {
    Reminder: null;
} | {
    Announcement: null;
} | {
    ProjectMatch: null;
} | {
    Offer: null;
}): NotificationType {
    return "RegistrationUpdate" in value ? NotificationType.RegistrationUpdate : "Reminder" in value ? NotificationType.Reminder : "Announcement" in value ? NotificationType.Announcement : "ProjectMatch" in value ? NotificationType.ProjectMatch : "Offer" in value ? NotificationType.Offer : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Failed: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): PaymentRecordStatus {
    return "Failed" in value ? PaymentRecordStatus.Failed : "Completed" in value ? PaymentRecordStatus.Completed : "Pending" in value ? PaymentRecordStatus.Pending : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n48(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n34(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationRecord>): Array<NotificationRecord> {
    return value.map((x)=>from_candid_NotificationRecord_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectRecord>): Array<ProjectRecord> {
    return value.map((x)=>from_candid_ProjectRecord_n14(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CandidateProfile>): Promise<Array<CandidateProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CandidateProfile_n27(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRecord>): Array<PaymentRecord> {
    return value.map((x)=>from_candid_PaymentRecord_n41(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_NotificationType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectCategory): _ProjectCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectInput): _ProjectInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ProjectStatus;
    title: string;
    description: string;
    deadline: Timestamp;
    category: ProjectCategory;
    requirements: string;
    budget: string;
}): {
    status: _ProjectStatus;
    title: string;
    description: string;
    deadline: _Timestamp;
    category: _ProjectCategory;
    requirements: string;
    budget: string;
} {
    return {
        status: to_candid_ProjectStatus_n10(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        deadline: value.deadline,
        category: to_candid_ProjectCategory_n12(_uploadFile, _downloadFile, value.category),
        requirements: value.requirements,
        budget: value.budget
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    Closed: null;
} | {
    Active: null;
} | {
    Draft: null;
} {
    return value == ProjectStatus.Closed ? {
        Closed: null
    } : value == ProjectStatus.Active ? {
        Active: null
    } : value == ProjectStatus.Draft ? {
        Draft: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectCategory): {
    Bridal: null;
} | {
    MusicVideo: null;
} | {
    ECommerce: null;
} | {
    Fashion: null;
} | {
    Jewellery: null;
} | {
    International: null;
} | {
    WebSeries: null;
} | {
    BrandPromotion: null;
} | {
    Catalogue: null;
} {
    return value == ProjectCategory.Bridal ? {
        Bridal: null
    } : value == ProjectCategory.MusicVideo ? {
        MusicVideo: null
    } : value == ProjectCategory.ECommerce ? {
        ECommerce: null
    } : value == ProjectCategory.Fashion ? {
        Fashion: null
    } : value == ProjectCategory.Jewellery ? {
        Jewellery: null
    } : value == ProjectCategory.International ? {
        International: null
    } : value == ProjectCategory.WebSeries ? {
        WebSeries: null
    } : value == ProjectCategory.BrandPromotion ? {
        BrandPromotion: null
    } : value == ProjectCategory.Catalogue ? {
        Catalogue: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    RegistrationUpdate: null;
} | {
    Reminder: null;
} | {
    Announcement: null;
} | {
    ProjectMatch: null;
} | {
    Offer: null;
} {
    return value == NotificationType.RegistrationUpdate ? {
        RegistrationUpdate: null
    } : value == NotificationType.Reminder ? {
        Reminder: null
    } : value == NotificationType.Announcement ? {
        Announcement: null
    } : value == NotificationType.ProjectMatch ? {
        ProjectMatch: null
    } : value == NotificationType.Offer ? {
        Offer: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
async function to_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n60(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
