/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by TanStack Router

import { createFileRoute, createRootRoute } from "@tanstack/react-router";

// Import the actual components
import { Route as rootRoute } from "./routes/__root";
import { Route as AdminCandidateDetailRoute } from "./routes/admin/candidates/$candidateId";
import { Route as AdminCandidatesIndexRoute } from "./routes/admin/candidates/index";
import { Route as AdminDashboardRoute } from "./routes/admin/dashboard";
import { Route as AdminNotificationsRoute } from "./routes/admin/notifications";
import { Route as AdminProjectDetailRoute } from "./routes/admin/projects/$projectId";
import { Route as AdminProjectsIndexRoute } from "./routes/admin/projects/index";
import { Route as AdminSettingsRoute } from "./routes/admin/settings";
import { Route as ApplyRoute } from "./routes/apply";
import { Route as CandidateDashboardRoute } from "./routes/candidate/dashboard";
import { Route as CandidatePortfolioRoute } from "./routes/candidate/portfolio";
import { Route as CandidateProfileRoute } from "./routes/candidate/profile";
import { Route as IndexRoute } from "./routes/index";
import { Route as PaymentFailedRoute } from "./routes/payment/failed";
import { Route as PaymentSuccessRoute } from "./routes/payment/success";

const rootTree = rootRoute.addChildren([
  IndexRoute,
  ApplyRoute,
  PaymentSuccessRoute,
  PaymentFailedRoute,
  CandidateDashboardRoute,
  CandidateProfileRoute,
  CandidatePortfolioRoute,
  AdminDashboardRoute,
  AdminCandidatesIndexRoute,
  AdminCandidateDetailRoute,
  AdminProjectsIndexRoute,
  AdminProjectDetailRoute,
  AdminNotificationsRoute,
  AdminSettingsRoute,
]);

export const routeTree = rootTree;
